### ISSUE TITLE
add commercial square feet to FAR calculation

### ISSUE THREAD

**Issue by tbuckl** [MetropolitanTransportationCommission/tpp_ceqa_map_for_pba_17#7]
((Units*1000) + comm. square feet)/area_sq ft

**Comment by tbuckl** [comment]
This was out of scope/timeline

**Comment by dvautin1** [comment]
@tombuckley - we need commercial sqft included in the calculation.

**Comment by tbuckl** [comment]
resolved at this commit https://github.com/MetropolitanTransportationCommission/tpp_ceqa_map_for_pba_17/commit/8179835cf59b0e258ed510ac3f4990fe62394b6f
